### ISSUE TITLE
multiple instance of an auxtag 

### ISSUE THREAD

**Issue by dozy** [wtsi-npg/bambi#47]
for the bambi read2tags function:

  1. where there is a clash between --tags (or --qtags) and an existing auxtag on a read: by default error, with flag[s] for optional replace or merge (global, not per tag)

  2. when multiple auxtags are specified (via command line flags), merge all values to one instance of the tag (as in i2b).

**Comment by jenniferliddle** [comment]
Fixed by PR #46
