### ISSUE TITLE
Bambi decode statistics don't show the figures for dual tag reads

### ISSUE THREAD

**Issue by valeriuo** [wtsi-npg/bambi#69]
A issue came up when using tag pairs for sequence matching: in some cases the start and end tags belong to different pairs (aka tag hopping). 
Bambi decode statistics don't account for this issue. Thus, the code has to be extended with an improved matching algorithm and supplementary variables to count the various scenarios: first tag match, second tag match, first tag match with one base mismatch etc.

**Comment by jenniferliddle** [comment]
Fixed by PR #80
